### ISSUE TITLE
Using it inside a modal

### ISSUE THREAD

**Issue by ronyrun** [ivanthecrazy/ion-place-autocomplete#1]
Hello, 

Thank you very much for your solution !

I encounter difficulties to use your autocomplete inside a modal,
Do you have any working example?

Thank you very much.

**Comment by ivanthecrazy** [comment]
@ronyrun 

I believe you can play with z-index for .ion-place-tools-autocomplete-dropdown

Can you show me your code on codepen or somewhere else? I'll try to find a solution, but I believe that simple z-index adjustment will work.
