### ISSUE TITLE
Plugin disappear 

### ISSUE THREAD

**Issue by umashankard** [ivanthecrazy/ion-place-autocomplete#15]
Why this plugin not working ,

**http://devfanaticblog.com/blog/ion/ion-place-autocomplete.js
http://devfanaticblog.com/blog/ion/ion-place-autocomplete.css**

Because these url plugin i have referred on my mobile application.

Unfortunately, three days before my application not working in live. My app shows white screen

I have checked in local, after that i have realized these plugin is a root cause. Now i have download from git and refer its working good.

My question is , Why this happened.

,
Thanks in advance

**Comment by ivanthecrazy** [comment]
Nobody promise you to keep these files. No one owes you anything here.
