### ISSUE TITLE
How to style this with Ionic  <label class="item item-input">

### ISSUE THREAD

**Issue by xiaofanwu** [ivanthecrazy/ion-place-autocomplete#4]
Thank you so much for making this! It is extremely easy to use. I do have one question. I was wondering how should I style the CCS sheet, so that the input box can become part of item item-input class. Right now, it will only work if it on the top by itself. I want it to be part of a list of item like below. thank you!
![screen shot 2016-02-06 at 3 43 36 pm](https://cloud.githubusercontent.com/assets/14242946/12867235/6c0815ac-cce8-11e5-985c-ba381376f31e.png)

**Comment by kingleroyg** [comment]
Hi @xiaofanwu check out the `ion-place-autocomplete.js`
and edit the `template` variable . it should be easy from there

**Comment by ivanthecrazy** [comment]
it works just like this
<div class="list">
        <ion-google-place placeholder="From" ng-model="data.from"></ion-google-place>
        <ion-google-place placeholder="To" ng-model="data.from"></ion-google-place>
</div>
Template editing is not required
