### ISSUE TITLE
Integration with map

### ISSUE THREAD

**Issue by valix85** [ivanthecrazy/ion-place-autocomplete#5]
Hi, can I integrate new position with google map, such as a marker? it's possible retrive latlng parameter?
i would like show marker in find position and adjust it on a map for set a location manually after.

in template if i change <div class="item item-input ion-place-tools-autocomplete"> with a label doesn't fire event changeLocation alert... how can i fix it?

Thank you

**Comment by valix85** [comment]
hi, i create it:
var mye = new CustomEvent('showMap');
[....]
// Open the modal
  $scope.nuovaAbitazione = function() {
    $scope.modalnew.show();
    document.body.dispatchEvent(mye);
  };

scope.map="";
$scope.geocoder = new google.maps.Geocoder();
$scope.locationChanged2="";
$scope.markers = [];


// Adds a marker to the map and push to the array.
function addMarker(location, map) {
  var image = 'img/homeMarker2.png';
  var marker = new google.maps.Marker({
    position: location,
    map: map,
    draggable: true,
    animation: google.maps.Animation.DROP,
    icon:image,
  });
  $scope.markers.push(marker);
}
// Sets the map on all markers in the array.
function setMapOnAll(map) {
  for (var i = 0; i < $scope.markers.length; i++) {
    $scope.markers[i].setMap(map); //associandoli a null non sn di nessuna mappa e quindi scompaiono se disegnati
  }
}
// Removes the markers from the map, but keeps them in the array.
function clearMarkers() {
  setMapOnAll(null);
}
// Deletes all markers in the array by removing references to them.
function deleteMarkers() {
  clearMarkers();
  $scope.markers = [];
}

$ionicPlatform.ready(function() {
  console.log("ready");
  function initMap() {

var options = {timeout: 10000, enableHighAccuracy: true}; 
  $cordovaGeolocation.getCurrentPosition(options).then(function(position){
    console.log("getCurrentPosition: \n"+JSON.stringify(position)); 
    var latlng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
     //var latlng = {lat: 45.1847250, lng: 9.1582070};
     var mapOptions = {
      center: latlng,
      zoom: 15,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    }; 
    $scope.map = new google.maps.Map(document.getElementById("map2"), mapOptions);
    deleteMarkers();
    addMarker(latlng, $scope.map);

    });    
  };
  $scope.locationChanged2 = function (location) {
   //alert(location);
   deleteMarkers();   
   geocodeAddress($scope.geocoder, $scope.map, location);
  };
  google.maps.event.addDomListener(document.body, "showMap", initMap);  
});

function geocodeAddress(geocoder, resultsMap, loc) {  
  geocoder.geocode({'address': loc}, function(results, status) {
    if (status === google.maps.GeocoderStatus.OK) {
      resultsMap.setCenter(results[0].geometry.location);
      /*
      var marker = new google.maps.Marker({
        map: resultsMap,
        position: results[0].geometry.location
      });
    */
    addMarker(results[0].geometry.location, resultsMap );
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}

in template if i change <div class="item item-input ion-place-tools-autocomplete"> with a label doesn't fire event changeLocation alert... how can i fix it?
I just use it on a list, every object, item, ecc.. aren't visibile after this directive...i have a bottom bar and disappear it.
I MUST correct it quickly...what can i do? please help me

**Comment by ivanthecrazy** [comment]
Take a look at map_demo.html in the repo. I believe it do something like you need
